<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
 <div class="col-md-4">
 <div class="thumbnail blog-article">
 <?php if ($post->isViewableForVisitor()): ?>
 <?php if ($featuredImage = $post->getFeaturedImage()): ?>
 <a href="<?php echo $post->getPermalink() ?>" class="img-responsive" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
 <img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
  <?php endif; ?>
  <div class="caption">
   <h3 class="thumbnail-label"><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h3>
  <p><?php echo $this->getBeforePostContentHtml() ?></p>
  <p><?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
				<?php echo $post->getPostExcerpt() ?>
			<?php else: ?>
				<?php $string = $post->getPostContent();
				$str = substr($string,0,200);
				echo $str;
				?>
			<?php endif; ?>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?></p>
		<p><?php echo $this->getAfterPostContentHtml() ?></p>
  </div>
 </div>   
</div>